# Playing over Changes

## Soloing over Fast Harmonic Rhythm {-}
It is not necessary to outline every single chord in a progression, especially when the changes are coming at a fast pace ("Outline" here means to play notes that differentiate a particular chord from the others before and after it. For example, soloing over **Am7-D7-Gmaj7**, one might emphasize the G (b7) on **Am7** since it will resolve nicely to F# (3) on **D7**).

With a fast tempo and/or harmonic rhythm, it is sometimes possible to reduce the song structure down to a few scales or arpeggios. This also applies to slower tempos, but in that case, it would be possible to emphasize the chord changes anyway.

The following list covers some common progressions, and some example arpeggios and scales over each.

Additionally, the superimpositions and substitutions discussed in the previous chapter work as well (e.g. playing the altered scale over a fast ii-V).

- **ii-V**
  - ii-V can be thought of as just V.
  - Arpeggios over ii-V:
    - V7: results in notes 11-6-R-b3 over the ii. Example: D7 over Am7-D7.
    - ii triad: results in notes 5-b7-9 over V. Example: Am triad over Am7-D7.
    - iim7: adds an 11th over V to the above triad.
    - viim7b5: results in notes 6-R-b3-5 over ii, and notes 3-5-b7-9 over V. Example: F#m7b5 over Am7-D7
  - Scale: the V7 dominant scale over ii-V is the Dorian mode when played over ii, and Mixolydian mode when played over V. Example: D dominant scale over Am7-D7.
- **iim7b5-V**
  - This situation is more complicated than with a major ii-V. In much of jazz music, the iim7b5 in a minor ii-V is frequently thought of as coming from the natural minor harmony, while the V is coming from harmonic minor (E.g. Am7b5 in Am7b5-D7 comes from G Natural Minor, or the related Bb major, and D7 comes from G Harmonic Minor). For this reason, one might use the iim7b5's related Natural Minor (Locrian mode) over iim7b5, and the V's related Harmonic Minor (Phrygian Dominant mode) over the V. One might also just play the V dominant scale as if going to major I. It is also possible to use the parent harmonic minor scale over both chords, which adds a gypsy jazz or flamenco flavor. This is the Locrian #6 mode when played over ii, and Phrygian Dominant when played over V. Example: G harmonic minor over Am7b5-D7.
  - Arpeggios over iim7b5-V:
    - iidim triad: results in notes 5-b7-b9 over V. Example: Bdim over Bm7b5-E7. 
  - Scales over iim7b5-V:
      - Locrian over iim7b5, Phrygian Dominant over V.
      - V7 dominant scale over both chords.
      - Parent Harmonic Minor scale over both chords.
- **I-vi**, as in **I-vi-ii-V**
  - I-vi can be thought of as either just I or just vi.
    - Arpeggios over I-vi:
      - Imaj7: results in notes b3-5-b7-9 over vi. Example: Cmaj7 over Cmaj7-Am7.
      - vim7: results in notes 6-R-3-5 over I; this is equivalent to playing a maj6 chord over I. Example: Am7 over Cmaj7-Am7.
      - iiim7: results in notes 3-5-7-9 over I, and notes 5-b7-9-11 over vi. Example: Em7 over Cmaj7-Am7.
    - Scale: the I major scale is the Aeolian mode when played over vi. Example: C major scale over Cmaj7-Am7.
- **I-iii**, as in **I-iii-ii-V**
  - I-iii can be thought of as ether just I or just iii.
    - Arpeggios over I-iii:
      - Imaj7: results in notes b6-R-b3-5 over iii. Example: Cmaj7 over Cmaj7-Em7.
      - iiim7: results in notes 3-5-7-9 over I. Example: Em7 over Cmaj7-Em7.
    - Scale: the I major scale is the Phrygian mode when played over iii. Example: C major scale over Cmaj7-Em7.
    

### Examples over tunes {-}

- Rhythm Changes (original rhythm)
  - A large part of this tune is based on a I-vi-ii-V  progression spanning two bars: **Bb6 - Gm7 | Cm7 - F7**. This can be simplified to **Bb6 | F7** or **Gm7 | F7**, reducing the number of chords from 2 to 1 per bar. Substitutions can also be used over the F7 bar (e.g., playing the Ab dominant scale over F7).

